### ISSUE TITLE
Feature: min/max position

### ISSUE THREAD

**Issue by BalassaMarton** [ma-lwa-re/dreamdesk#2]
This is a feature I miss from the yaasa desk, and I believe could be solved with the custom controller: custom min/max position for the table. This is useful when the desk is in a crammy space with objects below and above, and you don't want to rely on the collision detection mechanism (which would easily let the table crush my chair before backing up).
There should be 2 configuration values, `min_position` and `max_position`, and the controller should break the movement of the table when either is reached.

**Comment by BalassaMarton** [comment]
I guess setting these positions should be possible using the controller keys, eg. press Save and then up/down button.

**Comment by ma-lwa-re** [comment]
Hello!

Indeed this is a use case that would be really helpful to have with the provided remote. This feature can definitely be added by using a custom controller and defining a range within which the desk is allowed to move between.

Don't know if this is exactly what you are looking for, but currently, you can define a MIN/MAX height in centimeters in the [`logicdata.h`](https://github.com/ma-lwa-re/dreamdesk/blob/master/main/logicdata.h) header. The default range goes from 60cm to 120cm, although the absolute maximum supported by the desk is from 57cm to 123cm.

https://github.com/ma-lwa-re/dreamdesk/blob/31289d9a424f03e48afcb1b755a8dd8283dbfcae/main/logicdata.h#L26-L27

If you try to set a target value outside of this range, the controller will reject it and thus won't move.

https://github.com/ma-lwa-re/dreamdesk/blob/31289d9a424f03e48afcb1b755a8dd8283dbfcae/main/dreamdesk.c#L81-L84

Greetings 🙂

**Comment by BalassaMarton** [comment]
Oh wow, tbh I didn't dive into the code as I don't have the skills or equipment to build a controller anyway :D Impressive work btw, especially with that article.
