### ISSUE TITLE
PCB Board

### ISSUE THREAD

**Issue by Digl** [ma-lwa-re/dreamdesk#3]
Very nice work!
Could you also share the PCB Design for OSHPark?
BR, Matt

**Comment by ma-lwa-re** [comment]
Hey!

Thanks for your message. You should be able to upload this archive to OSHPark and send your card to production 🙂

[v2.5.zip](https://github.com/ma-lwa-re/dreamdesk/files/14185884/v2.5.zip)

**Comment by Digl** [comment]
awesome! thanks a lot for all your great work!

one last question: did you mention the pins of the logicdata controller anywhere? how do you connect the controller to the LIN component?
thx!

**Comment by ma-lwa-re** [comment]
You're welcome!

Depending on your desk controller, either replace your original remote with this board or use the additional unused port. I'm using the [DMPHub S](https://www.logicdata.net/product/dmphub-s/) from Logicdata. You can connect the board with the desk controller using a molex micro fit 2x2 cable. Pinout:
<img width="529" alt="Screenshot 2024-02-11 at 21 36 33" src="https://github.com/ma-lwa-re/dreamdesk/assets/47607368/606d00fe-f41e-440f-b703-d50694ba9d32">

**Comment by Digl** [comment]
perfect, i have a logicdata controller as well.
Thanks for everything!

**Comment by Digl** [comment]
Hi again! Sorry for the noob questions!
I am not an expert in soldering or hardware like this in general. Do you have a component list or the Kicad project? This might help me do what you achieved. I really like your solution to have the one board which does everything and would like to achieve that as well.
You don't plan on selling finished modules in the future, do you? (I would def be interested :) )
Thanks!
